# Generated by Django 3.0.8 on 2020-07-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dp_name',
            field=models.CharField(default='dpdpdp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan',
            field=models.CharField(default='cvcvcvcvcv', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='brokerage',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='totalAmount',
            field=models.FloatField(default=100.45),
            preserve_default=False,
        ),
    ]
