# Generated by Django 3.0.8 on 2020-07-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vc_t_user',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
