# Generated by Django 3.0.8 on 2020-07-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dpid',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
