# Generated by Django 3.0.8 on 2020-07-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_auto_20200725_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vc_t_order_queue',
            name='updated_quantity',
        ),
        migrations.AddField(
            model_name='vc_t_order',
            name='updated_quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
