# Generated by Django 3.0.8 on 2020-07-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_auto_20200721_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='isin_no',
            field=models.CharField(default='isin', max_length=12),
            preserve_default=False,
        ),
    ]
