# Generated by Django 3.0.8 on 2020-07-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_auto_20200724_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dpname',
            field=models.CharField(default='dpname', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_no',
            field=models.CharField(default='pan_no', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
