# Generated by Django 3.0.8 on 2020-08-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_auto_20200725_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dpid',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
