# Generated by Django 3.0.8 on 2020-08-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_auto_20200804_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(default=1234567890, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
