# Generated by Django 3.0.8 on 2020-08-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_customuser_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_no',
        ),
    ]
