# Generated by Django 3.0.8 on 2020-08-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_remove_customuser_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(default=9090909090, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
